[package]
name = "rust-sdk-prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
dotenv = "0.15.0"
ic-agent = "0.39.0"
ic-utils = "0.39.0"
<<<<<<< HEAD
ic-cdk = "0.16.0"
=======
>>>>>>> 3fd094905ddb84c55f251dfbef20aa4e0d99884a
tokio = { version = "1.40.0", features = ["full"] }
libflate = "=2.1.0"
serde_cbor = "0.11.0"
